---
title: EarthMessenger 的博客
description: EarthMessenger 的博客
bio: Keep it simple, stupid.
baseurl: ""
url: "https://blog.earthmessenger.xyz"
github_username: EarthMessenger
author: EarthMessenger

lang: zh-CN

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

collections: 
  posts:
    premalink: "/:year/:month/:day/:title/"
    output: true
  oi-notes:
    premalink: "/:collection/:path/"
    output: true
  docs:
    permalink: "/:collection/:path"
    output: true

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_oi-notes"
      type: "oi-notes"
    values:
      layout: "oi-notes"
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - CNAME

# vim:et:ts=2:sts=2:sw=2
